extends SceneTree
var game
func _initialize():
	call_deferred("run")
func press(label: String):
	for child in game.content.get_children():
		if child is Button and child.text == label:
			child.pressed.emit()
			return
	assert(false, "Missing button: " + label)
func run():
	game = load("res://main.tscn").instantiate()
	root.add_child(game)
	game.inventory.clear()
	game.completed.clear()
	game.discovered.clear()
	game.inventory = ["own_bag"]
	game.talk("ena")
	press("Anni kel")
	assert(game.completed.has("belongings"))
	game.inventory.append_array(["water","fruit","container"])
	game.talk("mira")
	press("Offer supplies")
	assert(game.completed.has("meal"))
	assert(not game.inventory.has("water"))
	game.inventory.append("forest_bag")
	game.talk("sanu")
	press("Offer the forest bag")
	assert(game.completed.has("bag"))
	game.inventory.append_array(["wood","stone","rope"])
	game.talk("tor")
	press("Offer repair materials")
	assert(game.completed.has("bridge"))
	game.account("tor","italpada","Witnessed")
	game.talk("lira")
	game.talk("oren")
	game.check_evidence("Lira: italpanu")
	assert(not game.completed.has("evidence"))
	game.check_evidence("Tor: italpada")
	assert(game.completed.has("evidence"))
	game.talk("neri")
	assert(game.completed.has("cove"))
	game.player.position = Vector3(2,0.1,6)
	game.save_game()
	game.completed.clear()
	game.load_game()
	assert(game.completed.has("cove"))
	assert(game.player.position.x == 2)
	game.show_notebook()
	game.show_inventory()
	game.show_map()
	game.inventory.clear()
	game.discovered.clear()
	game.completed.clear()
	game.player.position = Vector3(0,0.1,36)
	game.save_game()
	print("PASS: six quests, wrong/correct evidence, inventory, persistence, panels")
	quit()
